# Site settings
title: Paul Krush Home Page
description: Welcome to my personal website. I'm a software engineer and I love to write about programming, technology, and other topics that interest me.
domain: PaulKrush.com
baseurl: "" # the subpath of your site, e.g., /docs
url: "http://PaulKrush.com" # the base hostname & protocol for your site
author: Paul Krush

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Include additional directories
include:
  - _pages

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false

# Social media links
social_links:
  twitter: paulkrush
  github: pkrush

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/

# Comments
comments:
  provider: disqus
  disqus:
    shortname: your_disqus_shortname

# Enable live reload
livereload:
  enabled: true

# Highlighter
highlighter: rouge
